# Catppuccin Latte Theme para tmux

# Colores
thm_bg="#eff1f5"
thm_fg="#4c4f69"
thm_cyan="#179299"
thm_black="#e6e9ef"
thm_gray="#ccd0da"
thm_magenta="#8839ef"
thm_pink="#ea76cb"
thm_red="#d20f39"
thm_green="#40a02b"
thm_yellow="#df8e1d"
thm_blue="#1e66f5"
thm_orange="#fe640b"
thm_black4="#acb0be"

# Status bar
set -g status-style "bg=${thm_bg},fg=${thm_fg}"
set -g status-left-length 100
set -g status-right-length 100

# Formato de la barra de estado
set -g status-left "#[fg=${thm_bg},bg=${thm_blue},bold] #S #[fg=${thm_blue},bg=${thm_bg}]"
set -g status-right "#[fg=${thm_gray},bg=${thm_bg}]#[fg=${thm_fg},bg=${thm_gray}] %a %d-%m #[fg=${thm_blue},bg=${thm_gray}]#[fg=${thm_bg},bg=${thm_blue},bold] %H:%M:%S "

# Ventanas
set -g window-status-format "#[fg=${thm_fg},bg=${thm_bg}] #I #W "
set -g window-status-current-format "#[fg=${thm_bg},bg=${thm_magenta},bold] #I #W "
set -g window-status-separator ""

# Bordes de paneles
set -g pane-border-style "fg=${thm_gray}"
set -g pane-active-border-style "fg=${thm_blue}"

set -g popup-border-lines "rounded"

# Mensajes
set -g message-style "bg=${thm_orange},fg=${thm_bg}"
set -g message-command-style "bg=${thm_orange},fg=${thm_bg}"

# Modo de copia
set -g mode-style "bg=${thm_yellow},fg=${thm_bg}"
